import {
  AuthAccessReadScope,
  AuthOrchestrationOperateScope,
  AuthOrchestrationReadScope,
  AuthRelayReadScope,
  AuthRelayWriteScope,
  AuthReviewWriteScope,
  AuthTerminalOperateScope,
  ISSUES_WS_METHODS,
  ORCHESTRATION_V2_WS_METHODS,
  type AuthEnvironmentScope,
  WS_METHODS,
  WsRpcGroup,
} from "@t3tools/contracts";
import type * as RpcGroup from "effect/unstable/rpc/RpcGroup";

type WsRpcMethod = RpcGroup.Rpcs<typeof WsRpcGroup>["_tag"];

/**
 * Keep authorization coverage coupled to the RPC group itself. Adding an RPC to
 * `WsRpcGroup` without choosing a scope is a type error instead of a production
 * runtime failure.
 */
export const RPC_REQUIRED_SCOPES = {
  [ORCHESTRATION_V2_WS_METHODS.dispatchCommand]: AuthOrchestrationOperateScope,
  [ORCHESTRATION_V2_WS_METHODS.getWorkflowScript]: AuthOrchestrationReadScope,
  [ORCHESTRATION_V2_WS_METHODS.getTurnDiff]: AuthOrchestrationReadScope,
  [ORCHESTRATION_V2_WS_METHODS.getFullThreadDiff]: AuthOrchestrationReadScope,
  [ORCHESTRATION_V2_WS_METHODS.searchThreads]: AuthOrchestrationReadScope,
  [ORCHESTRATION_V2_WS_METHODS.getArchivedShellSnapshot]: AuthOrchestrationReadScope,
  [ORCHESTRATION_V2_WS_METHODS.getThreadProjection]: AuthOrchestrationReadScope,
  [ORCHESTRATION_V2_WS_METHODS.launchThread]: AuthOrchestrationOperateScope,
  [ORCHESTRATION_V2_WS_METHODS.subscribeArchivedShell]: AuthOrchestrationReadScope,
  [ORCHESTRATION_V2_WS_METHODS.subscribeShell]: AuthOrchestrationReadScope,
  [ORCHESTRATION_V2_WS_METHODS.subscribeThread]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsMutate]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverProbe]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetConfig]: AuthOrchestrationReadScope,
  [WS_METHODS.serverRefreshProviders]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateProvider]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateServer]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateServerWithProgress]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpsertKeybinding]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverRemoveKeybinding]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetSettings]: AuthOrchestrationReadScope,
  [WS_METHODS.serverUpdateSettings]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverDiscoverSourceControl]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetTraceDiagnostics]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetProcessDiagnostics]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetProcessResourceHistory]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetResourceTelemetryHistory]: AuthOrchestrationReadScope,
  [WS_METHODS.serverRetryResourceTelemetry]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetUsageSummary]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetProviderUsage]: AuthOrchestrationReadScope,
  [WS_METHODS.serverSignalProcess]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverReportClientActivity]: AuthOrchestrationReadScope,
  [WS_METHODS.serverReportHostPowerState]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetBackgroundPolicy]: AuthOrchestrationReadScope,
  [WS_METHODS.scheduledTasksList]: AuthOrchestrationReadScope,
  [WS_METHODS.scheduledTasksSubscribe]: AuthOrchestrationReadScope,
  [WS_METHODS.scheduledTasksUpsert]: AuthOrchestrationOperateScope,
  [WS_METHODS.scheduledTasksSetEnabled]: AuthOrchestrationOperateScope,
  [WS_METHODS.scheduledTasksDelete]: AuthOrchestrationOperateScope,
  [WS_METHODS.scheduledTasksRunNow]: AuthOrchestrationOperateScope,
  [WS_METHODS.cloudGetRelayClientStatus]: AuthRelayReadScope,
  [WS_METHODS.cloudInstallRelayClient]: AuthRelayWriteScope,
  [WS_METHODS.pullRequestsList]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsListStats]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsDetail]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsActivity]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsDiffFileContents]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsRunAction]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsComment]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsSubmitReview]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsReplyToThread]: AuthOrchestrationOperateScope,
  [WS_METHODS.pullRequestsSetThreadResolution]: AuthOrchestrationOperateScope,
  // Read scope like the reads it un-caches: refreshing is part of reading, and a read-only
  // client pressing refresh must not be told it may not look again.
  [WS_METHODS.pullRequestsInvalidate]: AuthOrchestrationReadScope,
  // The candidate list is a read like the detail beside it; asking somebody for a review is a
  // write like every other one.
  [WS_METHODS.pullRequestsReviewerCandidates]: AuthOrchestrationReadScope,
  [WS_METHODS.pullRequestsRequestReviewers]: AuthOrchestrationOperateScope,
  [WS_METHODS.sourceControlLookupRepository]: AuthOrchestrationReadScope,
  [WS_METHODS.sourceControlCloneRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.sourceControlPublishRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.projectsListEntries]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsReadFile]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsSearchContents]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsSearchEntries]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsWriteFile]: AuthOrchestrationOperateScope,
  [WS_METHODS.shellOpenInEditor]: AuthOrchestrationOperateScope,
  [WS_METHODS.filesystemBrowse]: AuthOrchestrationReadScope,
  [WS_METHODS.assetsCreateUrl]: AuthOrchestrationReadScope,
  [WS_METHODS.assetsPersistChatAttachments]: AuthOrchestrationOperateScope,
  [WS_METHODS.subscribeVcsStatus]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeResourceTelemetry]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsRefreshStatus]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsPull]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitRunStackedAction]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitResolvePullRequest]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitPreparePullRequestThread]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsListRefs]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsCreateWorktree]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsRemoveWorktree]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsCreateRef]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsSwitchRef]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsInit]: AuthOrchestrationOperateScope,
  [WS_METHODS.reviewGetDiffPreview]: AuthReviewWriteScope,
  [WS_METHODS.reviewGetDiffFileContents]: AuthReviewWriteScope,
  [WS_METHODS.terminalOpen]: AuthTerminalOperateScope,
  [WS_METHODS.terminalAttach]: AuthTerminalOperateScope,
  [WS_METHODS.terminalWrite]: AuthTerminalOperateScope,
  [WS_METHODS.terminalResize]: AuthTerminalOperateScope,
  [WS_METHODS.terminalClear]: AuthTerminalOperateScope,
  [WS_METHODS.terminalRestart]: AuthTerminalOperateScope,
  [WS_METHODS.terminalClose]: AuthTerminalOperateScope,
  [WS_METHODS.subscribeTerminalEvents]: AuthTerminalOperateScope,
  [WS_METHODS.subscribeTerminalMetadata]: AuthTerminalOperateScope,
  [WS_METHODS.previewOpen]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewNavigate]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewResize]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewRefresh]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewClose]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewList]: AuthOrchestrationReadScope,
  [WS_METHODS.previewReportStatus]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationConnect]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationRespond]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationFocusHost]: AuthOrchestrationOperateScope,
  [WS_METHODS.subscribePreviewEvents]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeDiscoveredLocalServers]: AuthOrchestrationReadScope,
  [WS_METHODS.previewStopDiscoveredServer]: AuthOrchestrationOperateScope,
  [WS_METHODS.subscribeServerConfig]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeServerLifecycle]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeAuthAccess]: AuthAccessReadScope,
  [WS_METHODS.subscribeBackgroundPolicy]: AuthOrchestrationReadScope,
  // The tracker has no scope of its own: it is environment-local state like every other
  // orchestration surface, so it reads with `orchestration:read` and writes with
  // `orchestration:operate`. A dedicated `issues:*` pair is a change to `AuthEnvironmentScope`,
  // not to this table.
  [ISSUES_WS_METHODS.getSnapshot]: AuthOrchestrationReadScope,
  [ISSUES_WS_METHODS.getDetail]: AuthOrchestrationReadScope,
  [ISSUES_WS_METHODS.getEvents]: AuthOrchestrationReadScope,
  [ISSUES_WS_METHODS.getEnrichmentRuns]: AuthOrchestrationReadScope,
  [ISSUES_WS_METHODS.getThreadLinks]: AuthOrchestrationReadScope,
  [ISSUES_WS_METHODS.commentsList]: AuthOrchestrationReadScope,
  [ISSUES_WS_METHODS.stream]: AuthOrchestrationReadScope,
  [ISSUES_WS_METHODS.create]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.update]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.delete]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.restore]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.bulkUpdate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.setSortOrder]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.createStatus]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.updateStatus]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.deleteStatus]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.reorderStatuses]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.createLabel]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.updateLabel]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.deleteLabel]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.milestoneCreate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.milestoneUpdate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.milestoneDelete]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.milestonesReorder]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.cycleCreate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.cycleUpdate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.cycleDelete]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.todoCreate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.todoUpdate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.todoDelete]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.todosReorder]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.relationCreate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.relationDelete]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.commentCreate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.commentUpdate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.commentDelete]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.uploadCommentAttachment]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.viewCreate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.viewUpdate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.viewDelete]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.viewsReorder]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.setKeyPrefix]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.importCsv]: AuthOrchestrationOperateScope,
  // Spending provider tokens and attaching a thread are both writes, so both take operate — the
  // panel that watches a run afterwards is a read like every other one.
  [ISSUES_WS_METHODS.startEnrichment]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.cancelEnrichment]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.linkThread]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.unlinkThread]: AuthOrchestrationOperateScope,
  // Intake reads the same way the tracker does. `slackListChannels` is a read of Slack rather
  // than of this database, but it is still a read, and it is what the channel picker calls.
  [ISSUES_WS_METHODS.slackGetStatus]: AuthOrchestrationReadScope,
  [ISSUES_WS_METHODS.slackListChannels]: AuthOrchestrationReadScope,
  // Handing this server a bot token is the most consequential write on the tracker — it is what
  // lets other people's messages become issues — so it takes operate like every other write.
  [ISSUES_WS_METHODS.slackSetToken]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.slackWatchCreate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.slackWatchUpdate]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.slackWatchDelete]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.triageAccept]: AuthOrchestrationOperateScope,
  [ISSUES_WS_METHODS.triageReject]: AuthOrchestrationOperateScope,
} as const satisfies Readonly<Record<WsRpcMethod, AuthEnvironmentScope>>;

export function requiredScopeForRpcMethod(method: string): AuthEnvironmentScope {
  if (!Object.hasOwn(RPC_REQUIRED_SCOPES, method)) {
    throw new Error(`RPC method ${method} has no declared authorization scope.`);
  }
  const requiredScope = RPC_REQUIRED_SCOPES[method as WsRpcMethod];
  if (requiredScope === undefined) {
    throw new Error(`RPC method ${method} has no declared authorization scope.`);
  }
  return requiredScope;
}
