/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PairRouteImport } from './routes/pair'
import { Route as OrchestratorRouteImport } from './routes/orchestrator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsUsageRouteImport } from './routes/settings.usage'
import { Route as SettingsSyncRouteImport } from './routes/settings.sync'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsScheduledTasksRouteImport } from './routes/settings.scheduled-tasks'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsProjectsRouteImport } from './routes/settings.projects'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsIssuesStatusesRouteImport } from './routes/settings.issues-statuses'
import { Route as SettingsIssuesMilestonesRouteImport } from './routes/settings.issues-milestones'
import { Route as SettingsIssuesMigrationRouteImport } from './routes/settings.issues-migration'
import { Route as SettingsIssuesLabelsRouteImport } from './routes/settings.issues-labels'
import { Route as SettingsIssuesIntakeRouteImport } from './routes/settings.issues-intake'
import { Route as SettingsIssuesImportRouteImport } from './routes/settings.issues-import'
import { Route as SettingsIssuesEnrichmentRouteImport } from './routes/settings.issues-enrichment'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsEnvironmentsRouteImport } from './routes/settings.environments'
import { Route as SettingsEmailRouteImport } from './routes/settings.email'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsCompanyTeamsRouteImport } from './routes/settings.company-teams'
import { Route as SettingsCompanyMembersRouteImport } from './routes/settings.company-members'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as ProjectsProjectKeyRouteImport } from './routes/projects.$projectKey'
import { Route as IssuesMilestonesRouteImport } from './routes/issues_.milestones'
import { Route as ConnectCallbackRouteImport } from './routes/connect_.callback'
import { Route as ChatThreadsRouteImport } from './routes/_chat.threads'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as SettingsProjectsProjectKeyRouteImport } from './routes/settings.projects_.$projectKey'
import { Route as IssuesMilestonesMilestoneIdRouteImport } from './routes/issues_.milestones_.$milestoneId'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as ChatThreadsDraftDraftIdRouteImport } from './routes/_chat.threads_.draft.$draftId'
import { Route as ChatThreadsEnvironmentIdThreadIdRouteImport } from './routes/_chat.threads_.$environmentId.$threadId'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestratorRoute = OrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsScheduledTasksRoute = SettingsScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIssuesStatusesRoute = SettingsIssuesStatusesRouteImport.update({
  id: '/issues-statuses',
  path: '/issues-statuses',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIssuesMilestonesRoute =
  SettingsIssuesMilestonesRouteImport.update({
    id: '/issues-milestones',
    path: '/issues-milestones',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsIssuesMigrationRoute = SettingsIssuesMigrationRouteImport.update({
  id: '/issues-migration',
  path: '/issues-migration',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIssuesLabelsRoute = SettingsIssuesLabelsRouteImport.update({
  id: '/issues-labels',
  path: '/issues-labels',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIssuesIntakeRoute = SettingsIssuesIntakeRouteImport.update({
  id: '/issues-intake',
  path: '/issues-intake',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIssuesImportRoute = SettingsIssuesImportRouteImport.update({
  id: '/issues-import',
  path: '/issues-import',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIssuesEnrichmentRoute =
  SettingsIssuesEnrichmentRouteImport.update({
    id: '/issues-enrichment',
    path: '/issues-enrichment',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEnvironmentsRoute = SettingsEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEmailRoute = SettingsEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompanyTeamsRoute = SettingsCompanyTeamsRouteImport.update({
  id: '/company-teams',
  path: '/company-teams',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompanyMembersRoute = SettingsCompanyMembersRouteImport.update({
  id: '/company-members',
  path: '/company-members',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectKeyRoute = ProjectsProjectKeyRouteImport.update({
  id: '/projects/$projectKey',
  path: '/projects/$projectKey',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesMilestonesRoute = IssuesMilestonesRouteImport.update({
  id: '/issues_/milestones',
  path: '/issues/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectCallbackRoute = ConnectCallbackRouteImport.update({
  id: '/connect_/callback',
  path: '/connect/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadsRoute = ChatThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsProjectsProjectKeyRoute =
  SettingsProjectsProjectKeyRouteImport.update({
    id: '/projects_/$projectKey',
    path: '/projects/$projectKey',
    getParentRoute: () => SettingsRoute,
  } as any)
const IssuesMilestonesMilestoneIdRoute =
  IssuesMilestonesMilestoneIdRouteImport.update({
    id: '/issues_/milestones_/$milestoneId',
    path: '/issues/milestones/$milestoneId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatThreadsDraftDraftIdRoute = ChatThreadsDraftDraftIdRouteImport.update({
  id: '/threads_/draft/$draftId',
  path: '/threads/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadsEnvironmentIdThreadIdRoute =
  ChatThreadsEnvironmentIdThreadIdRouteImport.update({
    id: '/threads_/$environmentId/$threadId',
    path: '/threads/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/email': typeof EmailRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orchestrator': typeof OrchestratorRoute
  '/pair': typeof PairRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/threads': typeof ChatThreadsRoute
  '/connect/callback': typeof ConnectCallbackRoute
  '/issues/milestones': typeof IssuesMilestonesRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/company-members': typeof SettingsCompanyMembersRoute
  '/settings/company-teams': typeof SettingsCompanyTeamsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/email': typeof SettingsEmailRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/issues-enrichment': typeof SettingsIssuesEnrichmentRoute
  '/settings/issues-import': typeof SettingsIssuesImportRoute
  '/settings/issues-intake': typeof SettingsIssuesIntakeRoute
  '/settings/issues-labels': typeof SettingsIssuesLabelsRoute
  '/settings/issues-migration': typeof SettingsIssuesMigrationRoute
  '/settings/issues-milestones': typeof SettingsIssuesMilestonesRoute
  '/settings/issues-statuses': typeof SettingsIssuesStatusesRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/issues/milestones/$milestoneId': typeof IssuesMilestonesMilestoneIdRoute
  '/settings/projects/$projectKey': typeof SettingsProjectsProjectKeyRoute
  '/threads/$environmentId/$threadId': typeof ChatThreadsEnvironmentIdThreadIdRoute
  '/threads/draft/$draftId': typeof ChatThreadsDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/email': typeof EmailRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orchestrator': typeof OrchestratorRoute
  '/pair': typeof PairRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/threads': typeof ChatThreadsRoute
  '/connect/callback': typeof ConnectCallbackRoute
  '/issues/milestones': typeof IssuesMilestonesRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/company-members': typeof SettingsCompanyMembersRoute
  '/settings/company-teams': typeof SettingsCompanyTeamsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/email': typeof SettingsEmailRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/issues-enrichment': typeof SettingsIssuesEnrichmentRoute
  '/settings/issues-import': typeof SettingsIssuesImportRoute
  '/settings/issues-intake': typeof SettingsIssuesIntakeRoute
  '/settings/issues-labels': typeof SettingsIssuesLabelsRoute
  '/settings/issues-migration': typeof SettingsIssuesMigrationRoute
  '/settings/issues-milestones': typeof SettingsIssuesMilestonesRoute
  '/settings/issues-statuses': typeof SettingsIssuesStatusesRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/issues/milestones/$milestoneId': typeof IssuesMilestonesMilestoneIdRoute
  '/settings/projects/$projectKey': typeof SettingsProjectsProjectKeyRoute
  '/threads/$environmentId/$threadId': typeof ChatThreadsEnvironmentIdThreadIdRoute
  '/threads/draft/$draftId': typeof ChatThreadsDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_chat': typeof ChatRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/email': typeof EmailRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orchestrator': typeof OrchestratorRoute
  '/pair': typeof PairRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRoute
  '/_chat/threads': typeof ChatThreadsRoute
  '/connect_/callback': typeof ConnectCallbackRoute
  '/issues_/milestones': typeof IssuesMilestonesRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/company-members': typeof SettingsCompanyMembersRoute
  '/settings/company-teams': typeof SettingsCompanyTeamsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/email': typeof SettingsEmailRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/issues-enrichment': typeof SettingsIssuesEnrichmentRoute
  '/settings/issues-import': typeof SettingsIssuesImportRoute
  '/settings/issues-intake': typeof SettingsIssuesIntakeRoute
  '/settings/issues-labels': typeof SettingsIssuesLabelsRoute
  '/settings/issues-migration': typeof SettingsIssuesMigrationRoute
  '/settings/issues-milestones': typeof SettingsIssuesMilestonesRoute
  '/settings/issues-statuses': typeof SettingsIssuesStatusesRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/issues_/milestones_/$milestoneId': typeof IssuesMilestonesMilestoneIdRoute
  '/settings/projects_/$projectKey': typeof SettingsProjectsProjectKeyRoute
  '/_chat/threads_/$environmentId/$threadId': typeof ChatThreadsEnvironmentIdThreadIdRoute
  '/_chat/threads_/draft/$draftId': typeof ChatThreadsDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/connect'
    | '/dashboard'
    | '/email'
    | '/issues'
    | '/login'
    | '/onboarding'
    | '/orchestrator'
    | '/pair'
    | '/register'
    | '/settings'
    | '/usage'
    | '/pull-requests'
    | '/threads'
    | '/connect/callback'
    | '/issues/milestones'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/company-members'
    | '/settings/company-teams'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/email'
    | '/settings/environments'
    | '/settings/general'
    | '/settings/issues-enrichment'
    | '/settings/issues-import'
    | '/settings/issues-intake'
    | '/settings/issues-labels'
    | '/settings/issues-migration'
    | '/settings/issues-milestones'
    | '/settings/issues-statuses'
    | '/settings/keybindings'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/scheduled-tasks'
    | '/settings/source-control'
    | '/settings/sync'
    | '/settings/usage'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/issues/milestones/$milestoneId'
    | '/settings/projects/$projectKey'
    | '/threads/$environmentId/$threadId'
    | '/threads/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/connect'
    | '/dashboard'
    | '/email'
    | '/issues'
    | '/login'
    | '/onboarding'
    | '/orchestrator'
    | '/pair'
    | '/register'
    | '/settings'
    | '/usage'
    | '/pull-requests'
    | '/threads'
    | '/connect/callback'
    | '/issues/milestones'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/company-members'
    | '/settings/company-teams'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/email'
    | '/settings/environments'
    | '/settings/general'
    | '/settings/issues-enrichment'
    | '/settings/issues-import'
    | '/settings/issues-intake'
    | '/settings/issues-labels'
    | '/settings/issues-migration'
    | '/settings/issues-milestones'
    | '/settings/issues-statuses'
    | '/settings/keybindings'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/scheduled-tasks'
    | '/settings/source-control'
    | '/settings/sync'
    | '/settings/usage'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/issues/milestones/$milestoneId'
    | '/settings/projects/$projectKey'
    | '/threads/$environmentId/$threadId'
    | '/threads/draft/$draftId'
  id:
    | '__root__'
    | '/'
    | '/_chat'
    | '/calendar'
    | '/connect'
    | '/dashboard'
    | '/email'
    | '/issues'
    | '/login'
    | '/onboarding'
    | '/orchestrator'
    | '/pair'
    | '/register'
    | '/settings'
    | '/usage'
    | '/_chat/pull-requests'
    | '/_chat/threads'
    | '/connect_/callback'
    | '/issues_/milestones'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/company-members'
    | '/settings/company-teams'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/email'
    | '/settings/environments'
    | '/settings/general'
    | '/settings/issues-enrichment'
    | '/settings/issues-import'
    | '/settings/issues-intake'
    | '/settings/issues-labels'
    | '/settings/issues-migration'
    | '/settings/issues-milestones'
    | '/settings/issues-statuses'
    | '/settings/keybindings'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/scheduled-tasks'
    | '/settings/source-control'
    | '/settings/sync'
    | '/settings/usage'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/issues_/milestones_/$milestoneId'
    | '/settings/projects_/$projectKey'
    | '/_chat/threads_/$environmentId/$threadId'
    | '/_chat/threads_/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  EmailRoute: typeof EmailRoute
  IssuesRoute: typeof IssuesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrchestratorRoute: typeof OrchestratorRoute
  PairRoute: typeof PairRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UsageRoute: typeof UsageRoute
  ConnectCallbackRoute: typeof ConnectCallbackRoute
  IssuesMilestonesRoute: typeof IssuesMilestonesRoute
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRoute
  IssuesMilestonesMilestoneIdRoute: typeof IssuesMilestonesMilestoneIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrator': {
      id: '/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof OrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/scheduled-tasks': {
      id: '/settings/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/settings/scheduled-tasks'
      preLoaderRoute: typeof SettingsScheduledTasksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/issues-statuses': {
      id: '/settings/issues-statuses'
      path: '/issues-statuses'
      fullPath: '/settings/issues-statuses'
      preLoaderRoute: typeof SettingsIssuesStatusesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/issues-milestones': {
      id: '/settings/issues-milestones'
      path: '/issues-milestones'
      fullPath: '/settings/issues-milestones'
      preLoaderRoute: typeof SettingsIssuesMilestonesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/issues-migration': {
      id: '/settings/issues-migration'
      path: '/issues-migration'
      fullPath: '/settings/issues-migration'
      preLoaderRoute: typeof SettingsIssuesMigrationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/issues-labels': {
      id: '/settings/issues-labels'
      path: '/issues-labels'
      fullPath: '/settings/issues-labels'
      preLoaderRoute: typeof SettingsIssuesLabelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/issues-intake': {
      id: '/settings/issues-intake'
      path: '/issues-intake'
      fullPath: '/settings/issues-intake'
      preLoaderRoute: typeof SettingsIssuesIntakeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/issues-import': {
      id: '/settings/issues-import'
      path: '/issues-import'
      fullPath: '/settings/issues-import'
      preLoaderRoute: typeof SettingsIssuesImportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/issues-enrichment': {
      id: '/settings/issues-enrichment'
      path: '/issues-enrichment'
      fullPath: '/settings/issues-enrichment'
      preLoaderRoute: typeof SettingsIssuesEnrichmentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/environments': {
      id: '/settings/environments'
      path: '/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof SettingsEnvironmentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/email': {
      id: '/settings/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof SettingsEmailRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/company-teams': {
      id: '/settings/company-teams'
      path: '/company-teams'
      fullPath: '/settings/company-teams'
      preLoaderRoute: typeof SettingsCompanyTeamsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/company-members': {
      id: '/settings/company-members'
      path: '/company-members'
      fullPath: '/settings/company-members'
      preLoaderRoute: typeof SettingsCompanyMembersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectKey': {
      id: '/projects/$projectKey'
      path: '/projects/$projectKey'
      fullPath: '/projects/$projectKey'
      preLoaderRoute: typeof ProjectsProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues_/milestones': {
      id: '/issues_/milestones'
      path: '/issues/milestones'
      fullPath: '/issues/milestones'
      preLoaderRoute: typeof IssuesMilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect_/callback': {
      id: '/connect_/callback'
      path: '/connect/callback'
      fullPath: '/connect/callback'
      preLoaderRoute: typeof ConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/threads': {
      id: '/_chat/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ChatThreadsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/projects_/$projectKey': {
      id: '/settings/projects_/$projectKey'
      path: '/projects/$projectKey'
      fullPath: '/settings/projects/$projectKey'
      preLoaderRoute: typeof SettingsProjectsProjectKeyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/issues_/milestones_/$milestoneId': {
      id: '/issues_/milestones_/$milestoneId'
      path: '/issues/milestones/$milestoneId'
      fullPath: '/issues/milestones/$milestoneId'
      preLoaderRoute: typeof IssuesMilestonesMilestoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/threads_/draft/$draftId': {
      id: '/_chat/threads_/draft/$draftId'
      path: '/threads/draft/$draftId'
      fullPath: '/threads/draft/$draftId'
      preLoaderRoute: typeof ChatThreadsDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/threads_/$environmentId/$threadId': {
      id: '/_chat/threads_/$environmentId/$threadId'
      path: '/threads/$environmentId/$threadId'
      fullPath: '/threads/$environmentId/$threadId'
      preLoaderRoute: typeof ChatThreadsEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatPullRequestsRoute: typeof ChatPullRequestsRoute
  ChatThreadsRoute: typeof ChatThreadsRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
  ChatThreadsEnvironmentIdThreadIdRoute: typeof ChatThreadsEnvironmentIdThreadIdRoute
  ChatThreadsDraftDraftIdRoute: typeof ChatThreadsDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatPullRequestsRoute: ChatPullRequestsRoute,
  ChatThreadsRoute: ChatThreadsRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
  ChatThreadsEnvironmentIdThreadIdRoute: ChatThreadsEnvironmentIdThreadIdRoute,
  ChatThreadsDraftDraftIdRoute: ChatThreadsDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsCompanyMembersRoute: typeof SettingsCompanyMembersRoute
  SettingsCompanyTeamsRoute: typeof SettingsCompanyTeamsRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsEmailRoute: typeof SettingsEmailRoute
  SettingsEnvironmentsRoute: typeof SettingsEnvironmentsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIssuesEnrichmentRoute: typeof SettingsIssuesEnrichmentRoute
  SettingsIssuesImportRoute: typeof SettingsIssuesImportRoute
  SettingsIssuesIntakeRoute: typeof SettingsIssuesIntakeRoute
  SettingsIssuesLabelsRoute: typeof SettingsIssuesLabelsRoute
  SettingsIssuesMigrationRoute: typeof SettingsIssuesMigrationRoute
  SettingsIssuesMilestonesRoute: typeof SettingsIssuesMilestonesRoute
  SettingsIssuesStatusesRoute: typeof SettingsIssuesStatusesRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsProjectsRoute: typeof SettingsProjectsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsScheduledTasksRoute: typeof SettingsScheduledTasksRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsProjectsProjectKeyRoute: typeof SettingsProjectsProjectKeyRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsCompanyMembersRoute: SettingsCompanyMembersRoute,
  SettingsCompanyTeamsRoute: SettingsCompanyTeamsRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsEmailRoute: SettingsEmailRoute,
  SettingsEnvironmentsRoute: SettingsEnvironmentsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIssuesEnrichmentRoute: SettingsIssuesEnrichmentRoute,
  SettingsIssuesImportRoute: SettingsIssuesImportRoute,
  SettingsIssuesIntakeRoute: SettingsIssuesIntakeRoute,
  SettingsIssuesLabelsRoute: SettingsIssuesLabelsRoute,
  SettingsIssuesMigrationRoute: SettingsIssuesMigrationRoute,
  SettingsIssuesMilestonesRoute: SettingsIssuesMilestonesRoute,
  SettingsIssuesStatusesRoute: SettingsIssuesStatusesRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsProjectsRoute: SettingsProjectsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsScheduledTasksRoute: SettingsScheduledTasksRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsProjectsProjectKeyRoute: SettingsProjectsProjectKeyRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  CalendarRoute: CalendarRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  EmailRoute: EmailRoute,
  IssuesRoute: IssuesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrchestratorRoute: OrchestratorRoute,
  PairRoute: PairRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UsageRoute: UsageRoute,
  ConnectCallbackRoute: ConnectCallbackRoute,
  IssuesMilestonesRoute: IssuesMilestonesRoute,
  ProjectsProjectKeyRoute: ProjectsProjectKeyRoute,
  IssuesMilestonesMilestoneIdRoute: IssuesMilestonesMilestoneIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
