// Generated by scripts/ios/build-focus-icons.mjs from the desktop Focus icon catalog.
enum PathwayFocusIconCatalog {
    struct Option: Identifiable {
        let name: String
        let label: String
        var id: String { name }
    }

    static let options: [Option] = [
        .init(name: "Briefcase", label: "Work"),
        .init(name: "House", label: "Home"),
        .init(name: "Heart", label: "Personal"),
        .init(name: "Star", label: "Favorites"),
        .init(name: "Rocket", label: "Launch"),
        .init(name: "GraduationCap", label: "Study"),
        .init(name: "BookOpen", label: "Reading"),
        .init(name: "Lightbulb", label: "Ideas"),
        .init(name: "Code2", label: "Code"),
        .init(name: "Terminal", label: "Development"),
        .init(name: "Palette", label: "Creative"),
        .init(name: "Music", label: "Music"),
        .init(name: "Camera", label: "Photography"),
        .init(name: "Plane", label: "Travel"),
        .init(name: "Dumbbell", label: "Fitness"),
        .init(name: "Gamepad2", label: "Games"),
        .init(name: "Coffee", label: "Break"),
        .init(name: "Sprout", label: "Growth"),
        .init(name: "Target", label: "Goals"),
        .init(name: "Zap", label: "Fast lane"),
        .init(name: "Brain", label: "Thinking"),
        .init(name: "Compass", label: "Explore"),
        .init(name: "FolderKanban", label: "Projects"),
        .init(name: "ClipboardList", label: "Planning"),
        .init(name: "CalendarDays", label: "Schedule"),
        .init(name: "Users", label: "Team"),
        .init(name: "Building2", label: "Business"),
        .init(name: "Laptop", label: "Computer"),
        .init(name: "Wrench", label: "Maintenance"),
        .init(name: "Hammer", label: "Build"),
        .init(name: "FlaskConical", label: "Experiments"),
        .init(name: "Microscope", label: "Research"),
        .init(name: "Landmark", label: "Finance"),
        .init(name: "PiggyBank", label: "Savings"),
        .init(name: "ShoppingBag", label: "Shopping"),
        .init(name: "Globe2", label: "World"),
        .init(name: "Mountain", label: "Outdoors"),
        .init(name: "Bike", label: "Cycling")
    ]
    private static let names = Set(options.map(\.name) + ["CircleDot", "Layers3"])

    static func assetName(for name: String) -> String {
        "focus-" + (names.contains(name) ? name : "CircleDot")
    }
}
