// Generated by cyndrbase. Do not edit.
import { anyApi, componentsGeneric } from "cyndrbase/server";
export const api = anyApi;
export const internal = anyApi;
export const components = componentsGeneric();
