#!/usr/bin/env bash
set -euo pipefail

umask 077

PLUGIN_PREFIX="PathwayComputerUsePlugin"

# The plugin goes in the user's home. KWin finds plugins through Qt's library
# paths, and the Plasma session env script Pathway writes puts this root on
# QT_PLUGIN_PATH - so an install needs no root at all, and this script never
# asks for any: a PATHWAY_KWIN_PLUGIN_DIR the user cannot write is an error, not
# a sudo prompt. The lib64/lib split is read off the system Qt rather than
# guessed, because it is a distro packaging choice; keep this in sync with
# resolveInstallTarget() in apps/server/src/computer/kwinPluginProvisioning.ts.
if [[ -d /usr/lib64/qt6/plugins ]]; then
    USER_QT_PLUGIN_ROOT="$HOME/.local/lib64/qt6/plugins"
else
    USER_QT_PLUGIN_ROOT="$HOME/.local/lib/qt6/plugins"
fi
PLUGIN_DIR="${PATHWAY_KWIN_PLUGIN_DIR:-$USER_QT_PLUGIN_ROOT/kwin/plugins}"
SOURCE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE_ROOT="${PATHWAY_KWIN_CACHE_ROOT:-${XDG_CACHE_HOME:-$HOME/.cache}/pathway/kwin-computer-use-plugin}"
STATE_ROOT="${PATHWAY_KWIN_STATE_ROOT:-${XDG_STATE_HOME:-$HOME/.local/state}/pathway/kwin-computer-use-plugin}"
BUILD_DIR="${PATHWAY_KWIN_BUILD_DIR:-$CACHE_ROOT/build}"
STAMP_FILE="$STATE_ROOT/install.stamp"
# In the state root, not the plugin directory: the lock has to be taken before
# anything is known about the plugin directory, and the state root is always
# the user's own. The server's provisioning takes its own lock in the plugin
# directory; the two serialize against each other through the build lock.
LOCK_FILE="$STATE_ROOT/install.lock"
# The highest plugin number ever handed out on this machine. Shared with
# allocatePluginId() in apps/server/src/computer/kwinPluginProvisioning.ts and
# deliberately kept by uninstall.sh: KWin pins a plugin id to the library it
# first loaded for the life of the compositor, so a number must never come
# back even after every file that carried it is gone.
PLUGIN_ID_COUNTER_FILE="$STATE_ROOT/plugin-id.counter"
BUILD_LOCK_FILE="$STATE_ROOT/build.lock"
# Must match s_service in pathwaycomputeruseplugin.cpp and COMPUTER_SERVICE in
# the server's kwinDbus.ts: it is the name the health check pins an owner for.
SERVICE_NAME="com.spiritdevs.pathway.ComputerUse"
# Where a distribution puts KWin's library and its cmake config: the lib64/lib
# split and the Debian multiarch directories, in the order HOST_LIBRARY_ROOTS
# in apps/server/src/computer/provisioning/hostToolchain.ts probes them. The
# overrides (colon-separated) exist for the script's tests.
IFS=: read -r -a KWIN_LIBRARY_ROOTS <<< "${PATHWAY_KWIN_LIBRARY_ROOTS:-/usr/lib64:/usr/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/aarch64-linux-gnu}"
IFS=: read -r -a SYSTEM_INCLUDE_ROOTS <<< "${PATHWAY_KWIN_INCLUDE_ROOTS:-/usr/include:/usr/local/include}"

FORCE=0
BUILD_ONLY=0

usage() {
    cat <<EOF
Usage: $0 [--force] [--build-only]

Builds the Pathway KWin plugin against the installed KWin headers, installs it
under the next unused versioned filename in the user's own plugin directory,
unloads older Pathway plugin ids, and loads the new id into the current KWin
session. Nothing needs root and nothing outside \$HOME is touched.

  --force           create and load a new version even when the signature is unchanged
  --noninteractive  accepted and ignored; kept so units generated by an older
                    systemd/enable.sh keep working
  --build-only      build against the local KWin headers, print the built .so
                    path, and stop. Nothing is installed, loaded, or stamped,
                    and no session bus is needed. This is what Pathway's own
                    provisioning calls when it has no prebuilt for this KWin:
                    the build lives here so there is exactly one of it, and the
                    install and load stay on the caller.
EOF
}

log() {
    printf '[pathway-kwin-plugin] %s\n' "$*"
}

warn() {
    printf '[pathway-kwin-plugin] WARNING: %s\n' "$*" >&2
}

die() {
    printf '[pathway-kwin-plugin] ERROR: %s\n' "$*" >&2
    exit 1
}

need_command() {
    command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)
            FORCE=1
            shift
            ;;
        --noninteractive)
            shift
            ;;
        --build-only)
            BUILD_ONLY=1
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            usage >&2
            die "Unknown argument: $1"
            ;;
    esac
done

need_command cmake
need_command ninja
need_command sha256sum
need_command stat
need_command awk
need_command grep
need_command sort
need_command flock
need_command mktemp
if (( BUILD_ONLY == 0 )); then
    need_command busctl
fi

mkdir -p "$CACHE_ROOT" "$STATE_ROOT"
if (( BUILD_ONLY == 0 )); then
    mkdir -p "$PLUGIN_DIR" || die "Cannot create the KWin plugin directory: $PLUGIN_DIR"
    [[ -w "$PLUGIN_DIR" ]] ||
        die "$PLUGIN_DIR is not writable. The plugin installs into your own home directory and never needs root; unset PATHWAY_KWIN_PLUGIN_DIR or point it at a directory you own."
fi

# Two locks, because --build-only shares the build directory with a full install
# but nothing else. Taking the install lock for a build that installs and stamps
# nothing would make two concurrent --build-only runs fight over a lock neither
# of them needs; sharing one build directory is the collision that is real.
# Ordering is always install then build, and --build-only only ever takes the
# second, so the two can never deadlock.
if (( BUILD_ONLY == 0 )); then
    exec 9>"$LOCK_FILE"
    if ! flock -n 9; then
        die "another install is already running"
    fi
fi

# Bounded rather than non-blocking: the caller of --build-only wants the built
# path, and a concurrent build will produce exactly the one it is waiting for.
BUILD_LOCK_WAIT_SECONDS=900

take_build_lock() {
    exec 8>"$BUILD_LOCK_FILE"
    if flock -n 8; then
        return 0
    fi
    log "another build is already running; waiting up to ${BUILD_LOCK_WAIT_SECONDS}s for it"
    flock -w "$BUILD_LOCK_WAIT_SECONDS" 8 ||
        die "timed out after ${BUILD_LOCK_WAIT_SECONDS}s waiting for the build lock: $BUILD_LOCK_FILE"
}

BUILT_PLUGIN_RELATIVE="kwin/plugins/${PLUGIN_PREFIX}.so"

# The directories the compiler and CMake's find modules search for a header:
# the system roots, then any prefix the caller pointed CMake or the compiler at.
header_present() {
    local root prefix
    for root in "${SYSTEM_INCLUDE_ROOTS[@]}"; do
        [[ -n "$root" && -f "$root/$1" ]] && return 0
    done
    local prefixes=()
    IFS=: read -r -a prefixes <<< "${CMAKE_PREFIX_PATH:-}"
    for prefix in "${prefixes[@]}"; do
        [[ -n "$prefix" && -f "$prefix/include/$1" ]] && return 0
    done
    IFS=: read -r -a prefixes <<< "${CPATH:-}"
    for prefix in "${prefixes[@]}"; do
        [[ -n "$prefix" && -f "$prefix/$1" ]] && return 0
    done
    return 1
}

library_present() {
    local root
    for root in "${KWIN_LIBRARY_ROOTS[@]}"; do
        [[ -n "$root" && -e "$root/$1" ]] && return 0
    done
    return 1
}

# KWin's cmake config find_dependency()s more than every distribution's
# kwin-devel pulls in (Vulkan's headers are the usual gap), and a header
# missing there fails the configure deep inside a find module with a message
# that names neither the file nor the package. So the dependencies this KWin's
# config actually declares are read off it and checked by name first, together
# with the plugin's own xkbcommon, and every gap is reported in one go. The
# server's localBuildToolingPresent() probes the same files.
check_build_dependencies() {
    local root config="" dependency
    local missing=()
    for root in "${KWIN_LIBRARY_ROOTS[@]}"; do
        if [[ -n "$root" && -f "$root/cmake/KWin/KWinConfig.cmake" ]]; then
            config="$root/cmake/KWin/KWinConfig.cmake"
            break
        fi
    done
    [[ -n "$config" ]] ||
        die "KWin's development files are not installed: no cmake/KWin/KWinConfig.cmake under ${KWIN_LIBRARY_ROOTS[*]}. Install kwin-devel (kwin-dev on Debian/Ubuntu, kwin6-devel on openSUSE, kwin on Arch)."

    header_present xkbcommon/xkbcommon.h ||
        missing+=("xkbcommon/xkbcommon.h (libxkbcommon-devel / libxkbcommon-dev)")
    while IFS= read -r dependency; do
        case "$dependency" in
            Vulkan)
                header_present vulkan/vulkan.h ||
                    missing+=("vulkan/vulkan.h (vulkan-headers / libvulkan-dev)")
                library_present libvulkan.so ||
                    missing+=("libvulkan.so (vulkan-loader-devel / libvulkan-dev / vulkan-icd-loader)")
                ;;
            epoxy)
                header_present epoxy/gl.h ||
                    missing+=("epoxy/gl.h (libepoxy-devel / libepoxy-dev)")
                ;;
            Libdrm)
                header_present xf86drm.h ||
                    missing+=("xf86drm.h (libdrm-devel / libdrm-dev)")
                ;;
            Wayland)
                header_present wayland-server.h ||
                    missing+=("wayland-server.h (wayland-devel / libwayland-dev)")
                ;;
        esac
    done < <(sed -n 's/^[[:space:]]*find_dependency([[:space:]]*\([A-Za-z0-9_]*\).*/\1/p' "$config")

    if (( ${#missing[@]} )); then
        die "cannot build the plugin: KWin's cmake config ($config) needs development files that are not installed: $(printf '%s; ' "${missing[@]}" | sed 's/; $//'). Install them and run this again."
    fi
}

# The build directory persists in the user's cache, but the source directory
# need not: a packaged app (an AppImage above all) mounts its payload at a new
# path on every launch, and CMake refuses a cache generated from another source
# directory outright ("does not match the source ... used to generate cache").
# Dropping the cache and CMakeFiles/ is enough for a fresh configure of the
# same build tree (ninja then recompiles against the new sources). The build
# directory itself is never removed, since PATHWAY_KWIN_BUILD_DIR can name a
# directory the user owns.
reset_foreign_cmake_cache() {
    local cache="$BUILD_DIR/CMakeCache.txt" cached_source physical_source
    [[ -f "$cache" ]] || return 0
    cached_source="$(sed -n 's/^CMAKE_HOME_DIRECTORY:INTERNAL=//p' "$cache" | head -n 1)" || true
    physical_source="$(cd -- "$SOURCE_DIR" && pwd -P)"
    if [[ -z "$cached_source" || "$cached_source" == "$SOURCE_DIR" || "$cached_source" == "$physical_source" ]]; then
        return 0
    fi
    log "the build cache in $BUILD_DIR was configured from $cached_source; reconfiguring it for $SOURCE_DIR"
    rm -rf -- "$cache" "$BUILD_DIR/CMakeFiles"
}

build_plugin() {
    check_build_dependencies
    take_build_lock
    reset_foreign_cmake_cache
    log "configuring the plugin build in $BUILD_DIR"
    cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
    cmake --build "$BUILD_DIR"
    [[ -f "$BUILD_DIR/$BUILT_PLUGIN_RELATIVE" ]] ||
        die "CMake did not produce $BUILD_DIR/$BUILT_PLUGIN_RELATIVE"
}

if (( BUILD_ONLY )); then
    build_plugin
    # The only thing on stdout that is not a log line, because the caller reads
    # the last line as the path.
    printf '%s\n' "$BUILD_DIR/$BUILT_PLUGIN_RELATIVE"
    exit 0
fi

source_hash() {
    (
        cd -- "$SOURCE_DIR"
        sha256sum \
            CMakeLists.txt \
            metadata.json \
            main.cpp \
            pathwaycomputeruseplugin.h \
            computeruseauth.h \
            pathwaycomputeruseplugin.cpp \
            pathwaycomputerusebuildinfo.h.in |
            sha256sum |
            awk '{ print $1 }'
    )
}

path_signature() {
    local path libdir
    for libdir in "${KWIN_LIBRARY_ROOTS[@]}"; do
        for path in "$libdir"/libkwin.so* "$libdir"/cmake/KWin/*.cmake; do
            if [[ -e "$path" ]]; then
                stat -Lc '%n:%i:%s:%Y' "$path"
            fi
        done
    done
}

rpm_signature() {
    if command -v rpm >/dev/null 2>&1; then
        rpm -q kwin kwin-libs kwin-devel 2>/dev/null || true
    fi
}

# The installed KWin version (what the next session will run), read off disk
# rather than asked of `kwin_wayland --version`, which aborts - and dumps core -
# when it is run outside a compositor start on some hosts. The soname symlink
# (libkwin.so.6 -> libkwin.so.6.7.4) names the exact release; KWin's cmake
# package version stands in on a machine without it. Empty when neither is
# there. Mirrors detectInstalledKwinVersion() in the server.
kwin_version() {
    local root link target version
    for root in "${KWIN_LIBRARY_ROOTS[@]}"; do
        for link in "$root"/libkwin.so.[0-9]*; do
            [[ -L "$link" && "${link##*/}" =~ ^libkwin\.so\.[0-9]+$ ]] || continue
            target="$(readlink -- "$link")" || continue
            if [[ "${target##*/}" =~ ^libkwin\.so\.([0-9]+(\.[0-9]+)+)$ ]]; then
                printf '%s\n' "${BASH_REMATCH[1]}"
                return 0
            fi
        done
    done
    for root in "${KWIN_LIBRARY_ROOTS[@]}"; do
        version="$(sed -n 's/^set(PACKAGE_VERSION "\([0-9][0-9.]*\)")$/\1/p' \
            "$root/cmake/KWin/KWinConfigVersion.cmake" 2>/dev/null | head -n 1)" || true
        if [[ -n "$version" ]]; then
            printf '%s\n' "$version"
            return 0
        fi
    done
}

# The version of the compositor in front of the user, asked of the compositor
# itself. After a KWin package upgrade this differs from what kwin_wayland
# --version prints until the next login, and the plugin can only load into the
# one that is running. Empty when the compositor cannot be asked.
running_kwin_version() {
    local response
    if response="$(busctl --user call org.kde.KWin /KWin org.kde.KWin supportInformation 2>/dev/null)"; then
        printf '%s\n' "$response" |
            grep -oE 'KWin version: [0-9]+(\.[0-9]+)+' |
            head -n 1 |
            sed 's/^KWin version: //' || true
    fi
}

# The KWin version the build in $BUILD_DIR was compiled against, from the
# header CMake generated for it. Empty when there is no build.
built_kwin_version() {
    sed -n 's/^#define PATHWAY_COMPUTER_USE_KWIN_VERSION "\(.*\)"$/\1/p' \
        "$BUILD_DIR/pathwaycomputerusebuildinfo.h" 2>/dev/null || true
}

current_signature_details() {
    printf 'source=%s\n' "$(source_hash)"
    printf 'plugin_dir=%s\n' "$PLUGIN_DIR"
    printf 'kwin_version=%s\n' "$(kwin_version)"
    printf 'rpm_signature<<EOF\n%s\nEOF\n' "$(rpm_signature)"
    printf 'path_signature<<EOF\n%s\nEOF\n' "$(path_signature)"
}

current_signature="$(current_signature_details | sha256sum | awk '{ print $1 }')"
installed_signature=""
installed_plugin_id=""
if [[ -f "$STAMP_FILE" ]]; then
    installed_signature="$(awk -F= '/^signature=/{ print $2; exit }' "$STAMP_FILE")"
    installed_plugin_id="$(awk -F= '/^plugin_id=/{ print $2; exit }' "$STAMP_FILE")"
fi

valid_plugin_id() {
    [[ "$1" =~ ^${PLUGIN_PREFIX}(V[0-9]+)?$ ]]
}

known_plugin_ids() {
    local path name
    local plugin_files=()

    shopt -s nullglob
    plugin_files=("$PLUGIN_DIR"/${PLUGIN_PREFIX}*.so)
    shopt -u nullglob

    {
        printf '%s\n' "$PLUGIN_PREFIX"
        for path in "${plugin_files[@]}"; do
            name="${path##*/}"
            name="${name%.so}"
            if valid_plugin_id "$name"; then
                printf '%s\n' "$name"
            fi
        done
    } | sort -u
}

extract_plugin_ids() {
    printf '%s\n' "$1" |
        grep -oE "${PLUGIN_PREFIX}(V[0-9]+)?" |
        sort -u || true
}

read_plugin_id_counter() {
    local value
    if [[ -f "$PLUGIN_ID_COUNTER_FILE" ]] && value="$(<"$PLUGIN_ID_COUNTER_FILE")" &&
        [[ "$value" =~ ^[[:space:]]*([0-9]+)[[:space:]]*$ ]]; then
        printf '%s\n' "${BASH_REMATCH[1]}"
    else
        printf '0\n'
    fi
}

write_plugin_id_counter() {
    local counter_tmp
    counter_tmp="$(mktemp "$STATE_ROOT/plugin-id.counter.XXXXXX")"
    printf '%s\n' "$1" >"$counter_tmp"
    mv -f "$counter_tmp" "$PLUGIN_ID_COUNTER_FILE"
}

# The next id must outrank every version KWin could know about, not just the
# ones in the target directory. A machine can carry installs in more than one
# root (an earlier install under /usr next to the home-directory root), and
# KWin pins a plugin id for the life of the compositor once it has loaded it -
# numbering from one root alone can hand back an id the compositor has already
# pinned to an older library, which fails at load with no reason given. The
# persisted counter covers the case no directory can: an uninstall that removed
# every file, followed by a reinstall in the same compositor session.
next_plugin_id() {
    local path name version dir
    local max_version
    max_version="$(read_plugin_id_counter)"
    local plugin_files=()
    local search_dirs=("$PLUGIN_DIR"
        /usr/lib64/qt6/plugins/kwin/plugins
        /usr/lib/qt6/plugins/kwin/plugins
        "$HOME/.local/lib64/qt6/plugins/kwin/plugins"
        "$HOME/.local/lib/qt6/plugins/kwin/plugins")

    for dir in "${search_dirs[@]}"; do
        shopt -s nullglob
        plugin_files=("$dir"/${PLUGIN_PREFIX}*.so)
        shopt -u nullglob
        for path in "${plugin_files[@]}"; do
            name="${path##*/}"
            if [[ "$name" =~ ^${PLUGIN_PREFIX}V([0-9]+)\.so$ ]]; then
                version="${BASH_REMATCH[1]}"
                if (( version > max_version )); then
                    max_version="$version"
                fi
            fi
        done
    done

    # The compositor's own lists cover ids whose files are gone but whose
    # libraries are still pinned in the running process.
    local kwin_ids response property
    for property in LoadedPlugins AvailablePlugins; do
        if response="$(busctl --user get-property org.kde.KWin /Plugins org.kde.KWin.Plugins "$property" 2>/dev/null)"; then
            kwin_ids="$(extract_plugin_ids "$response")"
            while IFS= read -r name; do
                if [[ "$name" =~ ^${PLUGIN_PREFIX}V([0-9]+)$ ]]; then
                    version="${BASH_REMATCH[1]}"
                    if (( version > max_version )); then
                        max_version="$version"
                    fi
                fi
            done <<< "$kwin_ids"
        fi
    done

    write_plugin_id_counter "$((max_version + 1))"
    printf '%sV%d\n' "$PLUGIN_PREFIX" "$((max_version + 1))"
}

# KWin's UnloadPlugin reply differs by version: some return `b`, newer ones are
# void. Treat a successful call with an empty or `b true` reply as unloaded and
# only `b false` as "was not loaded"; any call failure is fatal.
unload_plugin() {
    local plugin_id="$1"
    local response

    if ! response="$(busctl --user call org.kde.KWin /Plugins org.kde.KWin.Plugins UnloadPlugin s "$plugin_id" 2>&1)"; then
        die "KWin D-Bus UnloadPlugin failed for $plugin_id: $response"
    fi
    if [[ "$response" == *"b false"* ]]; then
        return 0
    fi
    log "unloaded $plugin_id"
}

# Staged next to the destination and renamed into place, so KWin - which
# rescans the directory on every AvailablePlugins read - never sees a
# half-copied .so under the final name. Same shape as installPluginBytes() in
# apps/server/src/computer/kwinPluginProvisioning.ts.
install_plugin() {
    local source_path="$1"
    local destination_path="$2"
    local staged="$destination_path.tmp"

    [[ ! -e "$destination_path" ]] ||
        die "refusing to overwrite an existing plugin build at $destination_path"
    if ! install -m 755 "$source_path" "$staged" || ! mv -f "$staged" "$destination_path"; then
        rm -f "$staged"
        die "install failed for $destination_path"
    fi
}

remove_plugin() {
    rm -f "$1"
}

write_install_stamp() {
    local stamp_tmp
    stamp_tmp="$(mktemp "$STATE_ROOT/install.stamp.XXXXXX")"
    {
        printf 'signature=%s\n' "$current_signature"
        printf 'plugin_id=%s\n' "$plugin_id"
        printf 'installed_at=%s\n' "$(date -Is)"
        printf 'plugin_path=%s\n' "$destination"
        # The server reads this back to explain a later LoadPlugin refusal:
        # KWin only accepts a plugin built against the running KWin version.
        printf 'kwin_version=%s\n' "$(kwin_version | head -n 1)"
    } >"$stamp_tmp"
    mv -f "$stamp_tmp" "$STAMP_FILE"
}

plugin_id=""
needs_install=1
if (( FORCE == 0 )) && [[ "$installed_signature" == "$current_signature" ]] && valid_plugin_id "$installed_plugin_id" && [[ -f "$PLUGIN_DIR/$installed_plugin_id.so" ]]; then
    plugin_id="$installed_plugin_id"
    needs_install=0
    log "signature is unchanged; reusing installed $plugin_id"
fi

expected_build_id=""
if (( needs_install )); then
    build_plugin
    built_plugin="$BUILD_DIR/$BUILT_PLUGIN_RELATIVE"
    # The compiled-in build id, read from the same generated header the build
    # just compiled. The health check below compares the running plugin's
    # reported id against it, which is the only proof the compositor is serving
    # the binary this run produced rather than an older generation that still
    # holds the service name. Only a fresh build carries this guarantee - a
    # reused install may legitimately predate the checkout's HEAD.
    expected_build_id="$(sed -n 's/^#define PATHWAY_COMPUTER_USE_BUILD_ID "\(.*\)"$/\1/p' \
        "$BUILD_DIR/pathwaycomputerusebuildinfo.h" 2>/dev/null || true)"

    plugin_id="$(next_plugin_id)"
    destination="$PLUGIN_DIR/$plugin_id.so"
    log "installing $plugin_id to $destination"
    install_plugin "$built_plugin" "$destination"
else
    destination="$PLUGIN_DIR/$plugin_id.so"
fi

# A KWin upgrade the running session has not picked up yet. The build matches
# the headers on disk, which is what the next session will run; the compositor
# in front of the user is still the old version and would refuse it. Install
# and stamp so the next login finds it, and leave the running plugin alone:
# unloading it now would take the feature away for the rest of this session
# in exchange for nothing.
built_version="$(built_kwin_version)"
running_version="$(running_kwin_version)"
if [[ -n "$built_version" && -n "$running_version" && "$built_version" != "$running_version" ]]; then
    if (( needs_install )); then
        write_install_stamp
    fi
    log "$plugin_id is built for KWin $built_version but this session is running KWin $running_version: the install takes effect at the next login. Nothing was unloaded, loaded, or removed."
    exit 0
fi

# Loaded-plugin discovery differs by KWin version: prefer the LoadedPlugins
# property, fall back to the loadedPlugins method. Prints the Pathway ids KWin
# reports as loaded; fails when neither query is answered.
query_loaded_plugin_ids() {
    local response
    if response="$(busctl --user get-property org.kde.KWin /Plugins org.kde.KWin.Plugins LoadedPlugins 2>/dev/null)" ||
        response="$(busctl --user call org.kde.KWin /Plugins org.kde.KWin.Plugins loadedPlugins 2>/dev/null)"; then
        extract_plugin_ids "$response"
        return 0
    fi
    return 1
}

# The timer's periodic run (and any other run on an unchanged install) ends
# here when the compositor is already running exactly the installed build and
# it holds the service: unloading and reloading it would drop the agent's
# session and seat for nothing. Anything else - the installed id not loaded,
# another Pathway id loaded beside it, nobody owning the service, loaded state
# that cannot be queried - falls through to the full load below.
if (( needs_install == 0 )) && loaded_now="$(query_loaded_plugin_ids)" &&
    [[ "$loaded_now" == "$plugin_id" ]] &&
    busctl --user call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus GetNameOwner s "$SERVICE_NAME" >/dev/null 2>&1; then
    log "$plugin_id is already loaded and serving $SERVICE_NAME; nothing to do. Nothing was unloaded or loaded."
    exit 0
fi

# Before touching anything that is loaded, make sure the running compositor can
# actually see the file that was just installed. AvailablePlugins rescans the
# plugin roots on read, so a fresh install shows up immediately - unless the
# install landed in a root the compositor was never told about (QT_PLUGIN_PATH
# is read once, at KWin startup). Failing here, with everything still loaded,
# beats the alternative: unloading the working plugin and then discovering the
# replacement is invisible.
if available_response="$(busctl --user get-property org.kde.KWin /Plugins org.kde.KWin.Plugins AvailablePlugins 2>/dev/null)"; then
    if [[ "$available_response" != *"\"$plugin_id\""* ]]; then
        die "KWin cannot see $plugin_id in $PLUGIN_DIR. The compositor reads QT_PLUGIN_PATH once at startup, so a first install into this root needs one log-out/log-in before it can load. Nothing was unloaded."
    fi
fi

# When KWin answers neither loaded-plugin query, every Pathway id we could have
# installed is unloaded instead.
old_plugin_ids=""
if old_plugin_ids="$(query_loaded_plugin_ids)"; then
    log "queried loaded KWin plugin ids"
else
    old_plugin_ids="$(known_plugin_ids)"
    log "KWin loaded-plugin queries are unavailable; trying known Pathway plugin ids"
fi

if [[ -n "$old_plugin_ids" ]]; then
    while IFS= read -r old_plugin_id; do
        [[ -n "$old_plugin_id" ]] || continue
        unload_plugin "$old_plugin_id"
    done <<< "$old_plugin_ids"
fi

# Plugin generations share KWin's D-Bus connection. Verify the compiled build
# identity below, rather than requiring a different connection owner.

load_response=""
if ! load_response="$(busctl --user call org.kde.KWin /Plugins org.kde.KWin.Plugins LoadPlugin s "$plugin_id" 2>&1)"; then
    die "KWin D-Bus LoadPlugin failed for $plugin_id: $load_response"
fi
if [[ "$load_response" != *"b true"* ]]; then
    die "KWin refused $plugin_id: $load_response. This usually means the plugin has a mismatching plugin version. Rebuild on this host against its installed kwin-devel package and inspect: journalctl --user -b -g 'mismatching plugin version'"
fi

service_owner_now=""
for _ in 1 2 3; do
    if owner_response="$(busctl --user call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus GetNameOwner s "$SERVICE_NAME" 2>/dev/null)"; then
        service_owner_now="$owner_response"
        break
    fi
    sleep 0.1
done
if [[ -z "$service_owner_now" ]]; then
    die "$plugin_id loaded, but nothing owns $SERVICE_NAME on the session bus, so the plugin did not register its service."
fi

health_response=""
if ! health_response="$(busctl --user call com.spiritdevs.pathway.ComputerUse /com/spiritdevs/pathway/ComputerUse com.spiritdevs.pathway.ComputerUse1 healthJson 2>&1)"; then
    die "plugin $plugin_id loaded, but healthJson failed: $health_response"
fi
printf '%s\n' "$health_response"

if [[ -n "$expected_build_id" ]]; then
    # busctl prints the JSON as an escaped string, so the quotes arrive as \".
    reported_build_id="$(printf '%s' "$health_response" | sed -n 's/.*\\"build\\":\\"\([^\\]*\)\\".*/\1/p')"
    if [[ -z "$reported_build_id" ]]; then
        log "healthJson reports no build id (older plugin interface); skipping the build identity check"
    elif [[ "$reported_build_id" != "$expected_build_id" ]]; then
        die "the compositor is serving build $reported_build_id, not the $expected_build_id this run just installed as $plugin_id - another plugin generation still owns $SERVICE_NAME"
    else
        log "the running plugin is the build this run installed ($reported_build_id)"
    fi
fi

# Superseded builds are deleted, not merely unloaded. KWin auto-loads any plugin
# in this directory whose metadata does not opt out, so an old build silently
# comes back on the next compositor start and races the current one for the
# com.spiritdevs.pathway.ComputerUse name - and the oldest registrant wins, which shadows the
# build that was just installed and makes an explicit LoadPlugin answer false.
# Only builds numbered below the id that just passed its health check go: a
# higher number is an install for an upgraded KWin waiting for the next login,
# not something this id supersedes. Same rule as pruneSupersededPlugins() in
# apps/server/src/computer/kwinPluginProvisioning.ts.
plugin_number() {
    if [[ "$1" =~ ^${PLUGIN_PREFIX}V([0-9]+)$ ]]; then
        printf '%s\n' "${BASH_REMATCH[1]}"
    else
        printf '0\n'
    fi
}

prune_old_plugins() {
    local path name removed=0 failed=0 keep_number
    local plugin_files=()
    keep_number="$(plugin_number "$plugin_id")"

    shopt -s nullglob
    plugin_files=("$PLUGIN_DIR"/${PLUGIN_PREFIX}*.so)
    shopt -u nullglob

    for path in "${plugin_files[@]}"; do
        name="${path##*/}"
        name="${name%.so}"
        if ! valid_plugin_id "$name" || (( $(plugin_number "$name") >= keep_number )); then
            continue
        fi
        unload_plugin "$name"
        if remove_plugin "$path"; then
            removed=$((removed + 1))
        else
            # A stale .so left behind wins the bus name on the next compositor
            # start (oldest registrant), shadowing the build this run installed
            # — never report that silently.
            warn "could not remove superseded plugin build $path; it will shadow $plugin_id on the next KWin start. Remove it manually."
            failed=$((failed + 1))
        fi
    done
    if (( removed )); then
        log "removed $removed superseded plugin build(s)"
    fi
    if (( failed )); then
        warn "$failed superseded plugin build(s) are still on disk"
    fi
}

prune_old_plugins

if (( needs_install )); then
    write_install_stamp
fi

log "Pathway KWin plugin is loaded as $plugin_id"
