import * as NodeFS from "node:fs";
import * as NodePath from "node:path";
import * as NodeURL from "node:url";

import { loadRepoEnv } from "./lib/public-config.ts";

const scriptDirectory = NodePath.dirname(NodeURL.fileURLToPath(import.meta.url));
const repoRoot = NodePath.dirname(scriptDirectory);
const outputPath = NodePath.join(repoRoot, "apps/pathway-ios/Config/Local.xcconfig");
const env = loadRepoEnv({ repoRoot });

function xcconfigValue(value: string | undefined): string {
  return (value?.trim() ?? "").replaceAll("//", "/$()/");
}

const values = {
  PATHWAY_CLERK_PUBLISHABLE_KEY: env.PATHWAY_CLERK_PUBLISHABLE_KEY,
  PATHWAY_CONVEX_URL: env.PATHWAY_CONVEX_URL,
  PATHWAY_RELAY_URL: env.PATHWAY_RELAY_URL,
} as const;
const requiredNames = ["PATHWAY_CLERK_PUBLISHABLE_KEY", "PATHWAY_CONVEX_URL"] as const;

const contents = [
  "// Generated by scripts/configure-pathway-ios.ts. Do not commit.",
  ...Object.entries(values).flatMap(([name, value]) =>
    value?.trim() ? [`${name} = ${xcconfigValue(value)}`] : [],
  ),
  "",
].join("\n");

NodeFS.mkdirSync(NodePath.dirname(outputPath), { recursive: true });
NodeFS.writeFileSync(outputPath, contents);

const missing = requiredNames.filter((name) => !values[name]?.trim());

console.log(
  missing.length === 0
    ? "Configured Pathway iOS public runtime identifiers."
    : `Wrote Pathway iOS configuration; missing ${missing.join(", ")}.`,
);
